language: julia

julia:
  - 1
  - nightly
notifications:
  email: false
coveralls: true
jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate();
                                    Pkg.build();'
        - julia --project=docs/ docs/make.jl
      after_success: skip
    - stage: "Documentation"
      julia: 1
      arch: arm64
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate();
                                    Pkg.build();'
        - julia --project=docs/ docs/make.jl
      after_success: skip
